#pnpm run build:docker-prod
packages:
  # "apps/*"
  #- "apps/wams-cfo-fe"
  #- "apps/wams-cms-fe"
  #- "apps/wams-gateway-fe"
  #- "apps/wams-hrm-fe"
  #- "apps/wams-integration-fe"
  #- "apps/wams-link-fe"
  #- "apps/wams-lms-fe"
  #- "apps/wams-quizz-fe"
  #- "apps/wams-rpm-fe"
  - "apps/wams-sysadmin-fe"
  - "packages/*"
