# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
resources:
  - repo: self
variables:
  tag: '$(Build.BuildId)'
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          #vmImage: 'ubuntu-latest'
          name: Default
        steps:
          - task: Docker@2
            displayName: Build and push quizz image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/quizz
              buildContext: ./
              dockerfile: 'dockerfiles/prod/quiz-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,quizz,prod