# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
resources:
  - repo: self
variables:
  tag: '$(Build.BuildId)'
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          #vmImage: 'ubuntu-latest'
          name: Default
        steps:
          - task: Docker@2
            displayName: Build and push gateway image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/gateway
              buildContext: ./
              dockerfile: 'dockerfiles/prod/gateway-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,gateway,prod
          - task: Docker@2
            displayName: Build and push sysadmin image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/sysadmin
              buildContext: ./
              dockerfile: 'dockerfiles/prod/sysadmin-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,sysadmin,prod
          - task: Docker@2
            displayName: Build and push rpm image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/rpm
              buildContext: ./
              dockerfile: 'dockerfiles/prod/rpm-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,rpm,prod
          - task: Docker@2
            displayName: Build and push cms image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/cms
              buildContext: ./
              dockerfile: 'dockerfiles/prod/cms-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,cms,prod
          - task: Docker@2
            displayName: Build and push cfo image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/cfo
              buildContext: ./
              dockerfile: 'dockerfiles/prod/cfo-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,cfo,prod
          - task: Docker@2
            displayName: Build and push quizz image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/quizz
              buildContext: ./
              dockerfile: 'dockerfiles/prod/quiz-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,quizz,prod
          - task: Docker@2
            displayName: Build and push hrm image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/hrm
              buildContext: ./
              dockerfile: 'dockerfiles/prod/hrm-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,hrm,prod
          - task: Docker@2
            displayName: Build and push link image to container registry
            inputs:
              command: buildAndPush
              repository: webapp/frontend/link
              buildContext: ./
              dockerfile: 'dockerfiles/prod/link-prod.Dockerfile'
              containerRegistry: 'prmDockerHubProd'
              tags: |
                fe,link,prod