export enum PermissionApplication {
    IMS = 'identity-service.',
    RPM = 'recruitment-service.',
    KMS = 'key-service.',
    MMS = 'messaging-service.',
    SMS = 'storage-service.',
    HRM = 'human-resources-service.',
    QUIZ = 'quiz-service.',
    CMS = 'calendar-service',
    LINK = 'link-service',
    INTEGRATION = 'integration-data'
}

export enum PermissionPage {
    THEME = '.theme.',
    CUSTOMER = '.customer.',
    ACCOUNT = '.account.',
    ACCOUNT_IMAGE = '.accountimage.',
    ACCOUNT_DETAIL = '.accountdetails.',
    DOMAIN = '.domain.',
    APPLICATION = '.app.',
    ROLE_INFO = '.roleinfo.',
    APP_PARAMETER = '.appparameter.',
    ANNEX = '.annex.',
    PASSWORD_CONFIG = '.passwordconfig.',
    PEB_CONFIG = '.pebconfig.',
    DIGETS_CONFIG = '.digestconfig.',
    TOKEN_CONFIG = '.tokenconfig.',
    SENDER_CONFIG = '.senderconfig.',
    STORAGE_CONFIG = '.storageconfig.',
    MSG_TEMPLATE = '.msgtemplate.',
    RESUME = '.resume.',
    RESUME_ADDITIONAL_INFO = '.resumeadditionalfiles.',
    RESUME_SHARE_INFO = '.resumeshareinfo.',
    JOB_OFFER_SHARE_INFO = '.joboffershareinfo.',
    RESUME_FILE = '.resumefile.',
    RESUME_IMAGE = '.resumeimage.',
    TIMELINE = '.timeline.',
    JOB_OFFER = '.joboffer.',
    JOB_OFFER_TEMPLATE = '.joboffertemplate.',
    WORKFLOW = '.workflow.',
    WORKFLOW_BOARD = '.workflowboard.',
    LEAVE_SUMMARY = '.leavesummary.',
    CONTRACT = '.contract.',
    CONTRACT_VACATION = '.vacation.',
    CONTRACT_FILE = '.contractfile.',
    CONTRACT_PAYMENT_SCHEDULE = '.paymentschedule.',
    EMPLOYEE = '.employee.',
    EMPLOYEE_IMAGE = '.employeeimage.',
    EMPLOYEE_CIN = '.cin.',
    EMPLOYEE_PASSPORT = '.passport.',
    EMPLOYEE_INSURANCE = '.insurancesecurity.',
    QUIZ = '.quiz.',
    CANDIDATE_QUIZ = '.candidatequiz.',
    VCALENDAR = '.vcalendar.',
    VEVENT = '.vevent.',
    APP_NEXT_CODE = '.appnextcode.',
    INTEGRATION_FLOW = '.integrationflow.',
    INTEGRATION_ORDER = '.integrationorder.',
    POST = '.post.',
    BLOG = '.blog.',
    BLOG_TALK = '.blogtalk.',
    PROPERTY = '.property.'
}

export enum PermissionAction {
    DELETE = 'delete',
    READ = 'read',
    WRITE = 'write'
}
